### ISSUE TITLE
How long it usually takes for virtuoso to finish load process?

### ISSUE THREAD

**Issue by qwelias** [dbpedia/Dockerized-DBpedia#11]
Currently it's running for over 12 hours.
Virtuoso allocated 3.9GiB RAM, 450GiB disk read total, 2GiB disk write total.
System has overall 16GiB of RAM, only 1.5GiB taken by OS.

First I ran
`docker run --rm -v /opt/dbpedia/data/en:/dbpedia-download aksw/dld-dist-dbpedia download  -l en`
then
`$ docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v /opt/dbpedia/data/en:/dbpedia-download --name dld-dbpedia aksw/dld-dist-dbpedia run-dld`

I'd drop a log here, but the system isn't very responsive now.

**Comment by qwelias** [comment]
I've been getting same messages as in #8 
After a restart it actually started to report progress.

**Comment by gone-phishing** [comment]
As mentioned in the issue [#8](https://github.com/dbpedia/Dockerized-DBpedia/issues/8)
this issue has more to do with Virtuoso functioning inside of docker than parsing of DBpedia datasets. 
In case you tweaked around any settings locally to get it working for yourself, please do update it here!

**Comment by qwelias** [comment]
Later I've figured it wasn't actual progress that were reported by the process, but recovering virtuoso after a restart.

I've tried to tweak some settings of Virtuoso by mounting `virtuoso.ini` through adding a *volume* in `dbpedia/dbpedia-dld.yml`, but it seems impossible because **aksw/dld-bootstrap** image rewrites *volume* section for some reason.

So I ended up making a [fork](https://github.com/qwemaze/DBpedia-docker) of another repo where I was able to apply my custom configs for Virtuoso
