### ISSUE TITLE
Missing code in the docu

### ISSUE THREAD

**Issue by kurzum** [dbpedia/Dockerized-DBpedia#15]
Hi @JJ-Author @holycrab13 ,
last docu commit, the code example was redacted from the README.md

This was actually the most important part of the docu, i.e. it was what I was showing to everybody during presentations. Could you include it again.

@holycrab13 Why don't you create a better collection than: https://databus.dbpedia.org/kurzum/collections/agro

I mean it would be nice to have a demo collection that loads the english cleaned mappings, the ontology and the geo-coordinates and  then do a nice query. In addition there should be a full collection URI given (like monthly pr an improved version of pre-release or the German one) here, so that people can also try the real thing.

**Comment by JJ-Author** [comment]
you can show the compose file directly. code duplication does not make sense since it needs to maintained twice, which was the case since it already changed.

**Comment by JJ-Author** [comment]
I can create the useful collection once @holycrab13 pushed the new collection interface so that i can use it as testing scenario
