### ISSUE TITLE
How to get all data from dbpedia/page (Using Python and SPRQL) #Question

### ISSUE THREAD

**Issue by dasisro-trendlab** [dbpedia/Dockerized-DBpedia#20]
Hello everyone,
I'm trying to get all the data from https://dbpedia.org/page/Asturias (Abstract, Place, Areacode...etc) using python but without success.
I tried with SPARQL (and Python) making some requests and the result was the same. Does someone know if there is a way to get the all data in a request?
Thanks very much in advance,
David

**Comment by joergrech** [comment]
Sorry for asking in a closed issue but I seem to have the same problem / misunderstanding. I cloned the repo and started the docker container with `latest-core` from the databus - which downloaded 5GB of data in the /data directory (the repo has a total of 9GB). 

However, the pages (e.g., Berlin) do not show dbo:abstract and other relations - do I need to use another databus repository, is the downloader still loading (however, after 5,2GB nothing changed) or is the full dbpedia not available and I need to use the public endpoints?

Btw. After ~4 hours the two container `dbpedia/virtuoso-sparql-endpoint-quickstart:latest` and `openlink/virtuoso-opensource-7` are still running and the "log" in the terminal shows lines like this:

```
store_1     | 12:29:18 * Monitor: CPU% is low while there are large numbers of runnable threads
store_1     | 12:30:20 * Monitor: High disk read (1)
store_1     | 12:30:45 *** read-ahead of a free or out of range page dp L=260741, database not necessarily corrupted.
store_1     | 12:31:18 * Monitor: CPU% is low while there are large numbers of runnable threads
store_1     | 12:31:56 Write wait on column page 568030.  Waits should be on the index leaf page, except when col page is held for read by background write
```

And furthermore: The files in the data directory "long-abstracts_lang=de_uris=en_8EC1.ttl.bz2" only contain the following text:
`<p>Temporary Redirect. Redirecting to <a href="http://akswnc7.informatik.uni-leipzig.de/dav/vehnem/replaced-iris/long-abstracts/2020.02.01/long-abstracts_lang=de_uris=en.ttl.bz2">http://akswnc7.informatik.uni-leipzig.de/dav/vehnem/replaced-iris/long-abstracts/2020.02.01/long-abstracts_lang=de_uris=en.ttl.bz2</a></p>
` 
Is this intended?
