### ISSUE TITLE
Repeat only incomplete downloads with wget when re-running download.sh

### ISSUE THREAD

**Issue by johann-petrak** [dbpedia/Dockerized-DBpedia#3]
If download.sh gets interrupted and re-run, all files will get downloaded again.
Adding these wget options will automatically only download the still incomplete files and only the part that is missing:
"-N -c".
Other options which may be useful to add could be "--progress=bar:force:noscroll --tries=1 --timeout=5 -nv"

**Comment by gone-phishing** [comment]
I've added the -N and -c option to wget in the latest commit. Thanks for pointing that out :)
