### ISSUE TITLE
Avoid using figlet

### ISSUE THREAD

**Issue by johann-petrak** [dbpedia/Dockerized-DBpedia#4]
This is easy to change, but figlet is a surprising dependency. It is not installed on many servers by default and is not really required so removeing it or replacing it by a simple "echo" could avoid some unnecessary time needed for people to figure out what is going on.

**Comment by johann-petrak** [comment]
Completely misunderstand here, sorry for the spam.

**Comment by gone-phishing** [comment]
Thanks for the feedback. Removed it and replaced with echo :)
