### ISSUE TITLE
Running docker prepare ends with error

### ISSUE THREAD

**Issue by johann-petrak** [dbpedia/Dockerized-DBpedia#5]
When I run this command 

```
docker run -ti --rm -v /var/run/docker.sock:/var/run/docker.sock:z --name dld-dbpedia aksw/dld-dist-dbpedia prepare  -l en
```

I get the following error:

```
Number of files downloaded:  55 / 55
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/docker/client.py", line 142, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3.4/site-packages/requests/models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dld/baselibs/python/dldbase/dockerutil.py", line 16, in __enter__
    self.client.version()
  File "/usr/lib/python3.4/site-packages/docker/api/daemon.py", line 78, in version
    return self._result(self._get(url), json=True)
  File "/usr/lib/python3.4/site-packages/docker/client.py", line 150, in _result
    self._raise_for_status(response)
  File "/usr/lib/python3.4/site-packages/docker/client.py", line 145, in _raise_for_status
    raise errors.NotFound(e, response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("b"client and server don't have same version (client : 1.21, server: 1.18)"")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dld/dld.py", line 366, in <module>
    main()
  File "/dld/dld.py", line 299, in main
    from config import DLDConfig
  File "/dld/config.py", line 12, in <module>
    class DLDConfig(object):
  File "/dld/config.py", line 51, in DLDConfig
    with dockerutil.docker_client() as dc:
  File "/dld/baselibs/python/dldbase/dockerutil.py", line 22, in __enter__
    err_repr=repr(e)))
RuntimeError: Encountered problem when interacting with your Docker Engine:
NotFound(HTTPError('404 Client Error: Not Found',),)
 * Is the Docker Daemon up and running?
 * Does the daemon use TLS? (currently unsupported by this tool)
```

I am also confused as to how one can specify where to persist the data after it has been imported from the downloaded files (not the downloaded files themselves): I think if one follows the steps in the README file, then all the data ends up being in /var/lib/docker which may be mounted on a partition with not enough space?

**Comment by neradis** [comment]
Concerning the error message: It seems like you are using an older, unsupported version of the Docker Engine (your engine seems to cater the Remote API Version `1.18`, which corresponds according to [the API docs](https://docs.docker.com/engine/reference/api/docker_remote_api/)) to version `1.6.*`. As written in the `README`, this tool only works with a Docker Engine of version `1.9` (and above). Can you please check you docker version with `docker --version`?
The error output in case of API version mismatch is indeed a bit confusing, I will check whether there is an easy way to provide more meaningful instruction to users when they use an incompatible Docker Engine.

I will quote and move your second question on the volumes location for the triplestore data to an issue of it's own.

**Comment by johann-petrak** [comment]
I am sorry, you are right! The docker version on the server I tried this on is old: 1.6.2. 
Sorry for bugspam.
