### ISSUE TITLE
control over volumes data location for triplestore files

### ISSUE THREAD

**Issue by neradis** [dbpedia/Dockerized-DBpedia#6]
johann-petrak wrote:

> I am also confused as to how one can specify where to persist the data after it has been imported from the downloaded files (not the downloaded files themselves): I think if one follows the steps in the README file, then all the data ends up being in /var/lib/docker which may be mounted on a partition with not enough space?

**Comment by neradis** [comment]
Thanks for pointing out this potential problem. I am not entirely decided yet, whether configurability for the volume mount point this is something that has to be covered for a one-liner scenario or whether it is okay to expect users who need control over the mount points to look a bit more into the configuration format of the [DLD bootstrap tool](https://dockerizing.github.io/bootstrap/) used under the hood to set up the triple store storage location.

Modifying the storage location manually would mean adding three YAML lines to [the DLD config file](https://github.com/dbpedia/Dockerized-DBpedia/blob/master/docker/dbpedia-dld.yml):

```
     store:
         image: aksw/dld-store-virtuoso7
         ports: ["8891:8890"]
+        volumes:
+            - /opt/dbpedia-tmp/import_store:/import_store
+            - /opt/dbpedia/vos-bd:/var/lib/virtuoso/db
         environment:
```

Followed by mounting your modified config file into the container:

```
docker run -ti -v /var/run/docker.sock:/var/run/docker.sock:z -v /opt/dbpedia/data/de:/dbpedia-download:z -v /path/to/modfied/dbpedia-dld.yml:/dbpedia-dld.yml --name dld-dbpedia aksw/dld-dist-dbpedia run-dld
```

(After having downloaded the dbpedia dump files in a separate step as documented).

@johann-petrak Is that in your opinion acceptable for cases when that requirement occurs?

**Comment by johann-petrak** [comment]
Yes - I think just adding this information to the documentation will be enough, so that people do not actually have to figure it out themselves by going through the DLD bootstrap tool documentation.
