### ISSUE TITLE
Add "getting started" documentation

### ISSUE THREAD

**Issue by bperel** [dbpedia/Dockerized-DBpedia#7]
Right now as far as I've seen there is no documentation regarding how to use the Docker container and the data it contains once it's ready. 
- Is it possible to run Sparql queries in the container ?
- Is it possible to run queries from the host using `docker exec` or wget with the port-forwarding that Docker provides ?
- Is there a way to manage the data which is inside the container using a Web interface ?

**Comment by gone-phishing** [comment]
We provide access to the SPARQL query web interface at [http://localhost:8891](http://localhost:8891) once the downloading and bulk loading task are finished. 
You can either use wget to get query results or directly make queries on the interface and select the desired output format.

**Comment by bperel** [comment]
Thanks, maybe adding this kind of information in the repo Wiki or in the README would help other users as well.

**Comment by jimkont** [comment]
Contributions are always welcome;)
