### ISSUE TITLE
docker for older version

### ISSUE THREAD

**Issue by D063520** [dbpedia/Dockerized-DBpedia#9]
Hi, 

I would like to set up an older DBpedia endpoint. I thought maybe the parameter

-b or --baseurl  : Set the baseurl for fetching the data-id file 
                   [Default: http://downloads.dbpedia.org/2016-04/core-i18n/lang/2016-04_dataid_lang.ttl]

is useful for that, but the default value is not pointing anywhere. So the concrete question is, can I use the script to install Dbpedia say 2015-04 in english?

Thank you
D063520

**Comment by D063520** [comment]
Ok, I see. Maybe you can put: 
http://downloads.dbpedia.org/2016-04/core-i18n/{lang}/2016-04_dataid_lang.ttl

**Comment by gone-phishing** [comment]
Thanks @D063520 for pointing that out. I have updated the documentation accordingly :)
